export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './measures.service';
import { MeasuresService } from './measures.service';
export * from './measures.serviceInterface';
export * from './neoplastic-entities.service';
import { NeoplasticEntitiesService } from './neoplastic-entities.service';
export * from './neoplastic-entities.serviceInterface';
export * from './patient-cases.service';
import { PatientCasesService } from './patient-cases.service';
export * from './patient-cases.serviceInterface';
export * from './risk-assessments.service';
import { RiskAssessmentsService } from './risk-assessments.service';
export * from './risk-assessments.serviceInterface';
export * from './stagings.service';
import { StagingsService } from './stagings.service';
export * from './stagings.serviceInterface';
export * from './systemic-therapies.service';
import { SystemicTherapiesService } from './systemic-therapies.service';
export * from './systemic-therapies.serviceInterface';
export * from './terminology.service';
import { TerminologyService } from './terminology.service';
export * from './terminology.serviceInterface';
export * from './tumor-markers.service';
import { TumorMarkersService } from './tumor-markers.service';
export * from './tumor-markers.serviceInterface';
export const APIS = [AuthService, MeasuresService, NeoplasticEntitiesService, PatientCasesService, RiskAssessmentsService, StagingsService, SystemicTherapiesService, TerminologyService, TumorMarkersService];
