/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodedConceptSchema } from './coded-concept-schema';


export interface NeoplasticEntityCreate { 
    /**
     * Indicates the case of the patient who\'s neoplasm(s) are recorded
     */
    caseId: string;
    /**
     * Relationship linking secondary and recurrent tumors to their primary origin or for distinguishing between different phases of the disease.
     */
    relationship: string;
    relatedPrimaryId?: string | null;
    /**
     * The date on which the existence of the neoplasm(s) was first asserted or acknowledged
     */
    assertionDate: string;
    /**
     * Anatomical location of the neoplasm(s)
     */
    topography: CodedConceptSchema;
    /**
     * Describes the cell type of the tumor and its biologic activity, in other words, the characteristics of the tumor itself
     */
    morphology: CodedConceptSchema;
    differentitation?: CodedConceptSchema | null;
    laterality?: CodedConceptSchema | null;
}

