/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NeoplasticRelationship = 'primary' | 'metastatic' | 'local_recurrence' | 'regional_recurrence';

export const NeoplasticRelationship = {
    Primary: 'primary' as NeoplasticRelationship,
    Metastatic: 'metastatic' as NeoplasticRelationship,
    LocalRecurrence: 'local_recurrence' as NeoplasticRelationship,
    RegionalRecurrence: 'regional_recurrence' as NeoplasticRelationship
};

