/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemicTherapySchema } from './systemic-therapy-schema';


export interface PaginatedSystemicTherapySchema { 
    count: number;
    items: Array<SystemicTherapySchema>;
}

