/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HomologousRecombinationDeficiencyInterpretationChoices } from './homologous-recombination-deficiency-interpretation-choices';


export interface HomologousRecombinationDeficiencyCreateSchema { 
    externalSource?: string | null;
    externalSourceId?: string | null;
    /**
     * Indicates the case of the patient who\'s lifestyle is assesed
     */
    caseId: string;
    /**
     * Clinically-relevant date at which the patient\'s genomic signature was assessed.
     */
    date: string;
    value?: number | null;
    interpretation?: HomologousRecombinationDeficiencyInterpretationChoices | null;
    category?: HomologousRecombinationDeficiencyCreateSchema.CategoryEnum;
}
export namespace HomologousRecombinationDeficiencyCreateSchema {
    export type CategoryEnum = 'homologous_recombination_deficiency';
    export const CategoryEnum = {
        HomologousRecombinationDeficiency: 'homologous_recombination_deficiency' as CategoryEnum
    };
}


