/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NeoplasticEntityRelationshipChoices = 'primary' | 'metastatic' | 'local_recurrence' | 'regional_recurrence';

export const NeoplasticEntityRelationshipChoices = {
    Primary: 'primary' as NeoplasticEntityRelationshipChoices,
    Metastatic: 'metastatic' as NeoplasticEntityRelationshipChoices,
    LocalRecurrence: 'local_recurrence' as NeoplasticEntityRelationshipChoices,
    RegionalRecurrence: 'regional_recurrence' as NeoplasticEntityRelationshipChoices
};

