/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NeoplasticEntityrelationshipChoices = 'primary' | 'metastatic' | 'local_recurrence' | 'regional_recurrence';

export const NeoplasticEntityrelationshipChoices = {
    Primary: 'primary' as NeoplasticEntityrelationshipChoices,
    Metastatic: 'metastatic' as NeoplasticEntityrelationshipChoices,
    LocalRecurrence: 'local_recurrence' as NeoplasticEntityrelationshipChoices,
    RegionalRecurrence: 'regional_recurrence' as NeoplasticEntityrelationshipChoices
};

