/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodedConceptSchema } from './coded-concept-schema';


export interface PaginatedCodedConceptSchema { 
    count: number;
    items: Array<CodedConceptSchema>;
}

