/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type QueryEntity = 'PatientCase' | 'PatientCaseDataCompletion' | 'NeoplasticEntity' | 'Staging' | 'StagingDomain' | 'TNMStaging' | 'FIGOStaging' | 'BinetStaging' | 'RaiStaging' | 'BreslowDepth' | 'ClarkStaging' | 'ISSStaging' | 'RISSStaging' | 'GleasonGrade' | 'INSSStage' | 'INRGSSStage' | 'WilmsStage' | 'RhabdomyosarcomaClinicalGroup' | 'LymphomaStaging' | 'TumorMarker' | 'RiskAssessment' | 'SystemicTherapy' | 'SystemicTherapyMedication' | 'PerformanceStatus' | 'Surgery' | 'Radiotherapy' | 'RadiotherapyDosage' | 'RadiotherapySetting' | 'TreatmentResponse' | 'Lifestyle' | 'ComorbiditiesAssessment' | 'ComorbiditiesPanel' | 'ComorbidityPanelCategory' | 'FamilyHistory' | 'TumorBoard' | 'MolecularTumorBoard' | 'UnspecifiedTumorBoard' | 'MolecularTherapeuticRecommendation' | 'AdverseEvent' | 'AdverseEventSuspectedCause' | 'AdverseEventMitigation' | 'Vitals' | 'GenomicVariant' | 'GenomicSignatureTypes' | 'GenomicSignature' | 'TumorMutationalBurden' | 'MicrosatelliteInstability' | 'LossOfHeterozygosity' | 'HomologousRecombinationDeficiency' | 'TumorNeoantigenBurden' | 'AneuploidScore';

export const QueryEntity = {
    PatientCase: 'PatientCase' as QueryEntity,
    PatientCaseDataCompletion: 'PatientCaseDataCompletion' as QueryEntity,
    NeoplasticEntity: 'NeoplasticEntity' as QueryEntity,
    Staging: 'Staging' as QueryEntity,
    StagingDomain: 'StagingDomain' as QueryEntity,
    TnmStaging: 'TNMStaging' as QueryEntity,
    FigoStaging: 'FIGOStaging' as QueryEntity,
    BinetStaging: 'BinetStaging' as QueryEntity,
    RaiStaging: 'RaiStaging' as QueryEntity,
    BreslowDepth: 'BreslowDepth' as QueryEntity,
    ClarkStaging: 'ClarkStaging' as QueryEntity,
    IssStaging: 'ISSStaging' as QueryEntity,
    RissStaging: 'RISSStaging' as QueryEntity,
    GleasonGrade: 'GleasonGrade' as QueryEntity,
    InssStage: 'INSSStage' as QueryEntity,
    InrgssStage: 'INRGSSStage' as QueryEntity,
    WilmsStage: 'WilmsStage' as QueryEntity,
    RhabdomyosarcomaClinicalGroup: 'RhabdomyosarcomaClinicalGroup' as QueryEntity,
    LymphomaStaging: 'LymphomaStaging' as QueryEntity,
    TumorMarker: 'TumorMarker' as QueryEntity,
    RiskAssessment: 'RiskAssessment' as QueryEntity,
    SystemicTherapy: 'SystemicTherapy' as QueryEntity,
    SystemicTherapyMedication: 'SystemicTherapyMedication' as QueryEntity,
    PerformanceStatus: 'PerformanceStatus' as QueryEntity,
    Surgery: 'Surgery' as QueryEntity,
    Radiotherapy: 'Radiotherapy' as QueryEntity,
    RadiotherapyDosage: 'RadiotherapyDosage' as QueryEntity,
    RadiotherapySetting: 'RadiotherapySetting' as QueryEntity,
    TreatmentResponse: 'TreatmentResponse' as QueryEntity,
    Lifestyle: 'Lifestyle' as QueryEntity,
    ComorbiditiesAssessment: 'ComorbiditiesAssessment' as QueryEntity,
    ComorbiditiesPanel: 'ComorbiditiesPanel' as QueryEntity,
    ComorbidityPanelCategory: 'ComorbidityPanelCategory' as QueryEntity,
    FamilyHistory: 'FamilyHistory' as QueryEntity,
    TumorBoard: 'TumorBoard' as QueryEntity,
    MolecularTumorBoard: 'MolecularTumorBoard' as QueryEntity,
    UnspecifiedTumorBoard: 'UnspecifiedTumorBoard' as QueryEntity,
    MolecularTherapeuticRecommendation: 'MolecularTherapeuticRecommendation' as QueryEntity,
    AdverseEvent: 'AdverseEvent' as QueryEntity,
    AdverseEventSuspectedCause: 'AdverseEventSuspectedCause' as QueryEntity,
    AdverseEventMitigation: 'AdverseEventMitigation' as QueryEntity,
    Vitals: 'Vitals' as QueryEntity,
    GenomicVariant: 'GenomicVariant' as QueryEntity,
    GenomicSignatureTypes: 'GenomicSignatureTypes' as QueryEntity,
    GenomicSignature: 'GenomicSignature' as QueryEntity,
    TumorMutationalBurden: 'TumorMutationalBurden' as QueryEntity,
    MicrosatelliteInstability: 'MicrosatelliteInstability' as QueryEntity,
    LossOfHeterozygosity: 'LossOfHeterozygosity' as QueryEntity,
    HomologousRecombinationDeficiency: 'HomologousRecombinationDeficiency' as QueryEntity,
    TumorNeoantigenBurden: 'TumorNeoantigenBurden' as QueryEntity,
    AneuploidScore: 'AneuploidScore' as QueryEntity
};

