/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TumorBoardSpecialties = 'unspecified' | 'molecular';

export const TumorBoardSpecialties = {
    Unspecified: 'unspecified' as TumorBoardSpecialties,
    Molecular: 'molecular' as TumorBoardSpecialties
};

