/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreate { 
    /**
     * 
     */
    password: string;
    lastLogin?: string | null;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    isActive?: boolean;
    title?: string | null;
    organization?: string | null;
    department?: string | null;
    /**
     * Level of access of the user in terms of permissions
     */
    accessLevel?: number;
}

