/**
 * django-allauth: Headless API
 *
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusOK } from './status-ok';
import { Session } from './session';


export interface ApiAllauthAppV1AuthSessionsGet200Response { 
    status: StatusOK;
    data: Array<Session>;
}
export namespace ApiAllauthAppV1AuthSessionsGet200Response {
}


