/**
 * django-allauth: Headless API
 *
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ProviderAccount } from './provider-account';
import { EmailAddress } from './email-address';


export interface ApiAllauthAppV1AuthProviderSignupGet200ResponseData { 
    email: Array<EmailAddress>;
    account: ProviderAccount;
    user: User;
}

