/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CohortStatisticsSchema { 
    ageAverage?: number | null;
    ageStdDev?: number | null;
    dataCompletionAverage?: number | null;
    dataCompletionStdDev?: number | null;
}

