/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Cohort { 
    /**
     * Cohort population
     */
    population: number;
    /**
     * 
     */
    id: string;
    externalSource?: string | null;
    externalSourceId?: string | null;
    /**
     * Name of the cohort
     */
    name: string;
    includeCriteria?: object | null;
    excludeCriteria?: object | null;
    /**
     * Whether the cohort is public
     */
    isPublic?: boolean;
    projectId?: string | null;
    /**
     * Cases composing the cohort
     */
    casesIds?: Array<string>;
    /**
     * Manually added cases
     */
    manualChoicesIds?: Array<string>;
    /**
     * Frozen cases
     */
    frozenSetIds?: Array<string>;
    /**
     * Human-readable description
     */
    description: string;
    /**
     * Whether the data has been anonymized
     */
    anonymized?: boolean;
    /**
     * Date-time when the resource was created
     */
    createdAt: string;
    updatedAt?: string | null;
    createdBy: string | null;
    updatedBy?: Array<string> | null;
}

