/**
 * django-allauth: Headless API
 *
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationResponseData } from './configuration-response-data';
import { StatusOK } from './status-ok';


export interface ConfigurationResponse { 
    data: ConfigurationResponseData;
    status: StatusOK;
}
export namespace ConfigurationResponse {
}


