/**
 * django-allauth: Headless API
 *
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseErrorsInner } from './error-response-errors-inner';


export interface ErrorResponse { 
    status?: ErrorResponse.StatusEnum;
    errors?: Array<ErrorResponseErrorsInner>;
}
export namespace ErrorResponse {
    export type StatusEnum = 400;
    export const StatusEnum = {
        NUMBER_400: 400 as StatusEnum
    };
}


