/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cohort } from './cohort';


export interface PaginatedCohort { 
    count: number;
    items: Array<Cohort>;
}

