/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { TumorMutationalBurdenStatusChoices } from './tumor-mutational-burden-status-choices';


export interface TumorMutationalBurden { 
    category?: TumorMutationalBurden.CategoryEnum;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    updatedAt: string;
    createdBy?: User | null;
    externalSource?: string | null;
    externalSourceId?: string | null;
    /**
     * Indicates the case of the patient who\'s lifestyle is assesed
     */
    caseId: string;
    /**
     * Clinically-relevant date at which the patient\'s genomic signature was assessed.
     */
    date: string;
    /**
     * The user(s) who updated the data since its creation
     */
    updatedBy?: Array<User>;
    /**
     * The actual tumor mutational burden (TMB) value in mutations/Mb
     */
    value: number;
    status?: TumorMutationalBurdenStatusChoices | null;
    /**
     * Human-readable description
     */
    description: string;
}
export namespace TumorMutationalBurden {
    export type CategoryEnum = 'tumor_mutational_burden';
    export const CategoryEnum = {
        TumorMutationalBurden: 'tumor_mutational_burden' as CategoryEnum
    };
}


