/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TumorMarkerpresenceChoices = 'positive' | 'negative' | 'indeterminate';

export const TumorMarkerpresenceChoices = {
    Positive: 'positive' as TumorMarkerpresenceChoices,
    Negative: 'negative' as TumorMarkerpresenceChoices,
    Indeterminate: 'indeterminate' as TumorMarkerpresenceChoices
};

