import { AdverseEvent, AdverseEventMitigation, AdverseEventSuspectedCause, AneuploidScore, AnyGenomicSignature, AnyTumorBoard, BinetStaging, BreslowDepth, ClarkStaging, ComorbiditiesAssessment, FamilyHistory, FIGOStaging, GenomicVariant, GleasonGrade, HomologousRecombinationDeficiency, INRGSSStage, INSSStage, ISSStaging, Lifestyle, LossOfHeterozygosity, LymphomaStaging, MicrosatelliteInstability, MolecularTherapeuticRecommendation, MolecularTumorBoard, NeoplasticEntity, PatientCase, PerformanceStatus, Radiotherapy, RadiotherapyDosage, RadiotherapySetting, RaiStaging, RhabdomyosarcomaClinicalGroup, RiskAssessment, RISSStaging, Surgery, SystemicTherapy, SystemicTherapyMedication, TherapyLine, TNMStaging, TreatmentResponse, TumorMarker, TumorMutationalBurden, TumorNeoantigenBurden, UnspecifiedTumorBoard, Vitals, WilmsStage } from "onconova-api-client";

export type OncologicalResource = 
    PatientCase | 
    NeoplasticEntity | 
    TNMStaging | 
    FIGOStaging | 
    BinetStaging | 
    RaiStaging | 
    BreslowDepth | 
    ClarkStaging | 
    ISSStaging | 
    RISSStaging | 
    GleasonGrade | 
    INSSStage | 
    INRGSSStage | 
    WilmsStage | 
    RhabdomyosarcomaClinicalGroup | 
    LymphomaStaging | 
    TumorMarker | 
    RiskAssessment | 
    TherapyLine | 
    SystemicTherapy | 
    SystemicTherapyMedication | 
    Surgery | 
    Radiotherapy | 
    RadiotherapyDosage | 
    RadiotherapySetting | 
    AdverseEvent | 
    AdverseEventSuspectedCause | 
    AdverseEventMitigation | 
    TreatmentResponse | 
    AnyTumorBoard | 
    UnspecifiedTumorBoard | 
    MolecularTumorBoard | 
    MolecularTherapeuticRecommendation | 
    PerformanceStatus | 
    Lifestyle | 
    FamilyHistory | 
    Vitals | 
    ComorbiditiesAssessment | 
    GenomicVariant | 
    AnyGenomicSignature | 
    TumorMutationalBurden | 
    MicrosatelliteInstability | 
    LossOfHeterozygosity | 
    HomologousRecombinationDeficiency | 
    TumorNeoantigenBurden | 
    AneuploidScore;
