export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './family-histories.service';
import { FamilyHistoriesService } from './family-histories.service';
export * from './family-histories.serviceInterface';
export * from './genomic-signatures.service';
import { GenomicSignaturesService } from './genomic-signatures.service';
export * from './genomic-signatures.serviceInterface';
export * from './genomic-variants.service';
import { GenomicVariantsService } from './genomic-variants.service';
export * from './genomic-variants.serviceInterface';
export * from './lifestyles.service';
import { LifestylesService } from './lifestyles.service';
export * from './lifestyles.serviceInterface';
export * from './measures.service';
import { MeasuresService } from './measures.service';
export * from './measures.serviceInterface';
export * from './neoplastic-entities.service';
import { NeoplasticEntitiesService } from './neoplastic-entities.service';
export * from './neoplastic-entities.serviceInterface';
export * from './patient-cases.service';
import { PatientCasesService } from './patient-cases.service';
export * from './patient-cases.serviceInterface';
export * from './performance-status.service';
import { PerformanceStatusService } from './performance-status.service';
export * from './performance-status.serviceInterface';
export * from './radiotherapies.service';
import { RadiotherapiesService } from './radiotherapies.service';
export * from './radiotherapies.serviceInterface';
export * from './risk-assessments.service';
import { RiskAssessmentsService } from './risk-assessments.service';
export * from './risk-assessments.serviceInterface';
export * from './stagings.service';
import { StagingsService } from './stagings.service';
export * from './stagings.serviceInterface';
export * from './surgeries.service';
import { SurgeriesService } from './surgeries.service';
export * from './surgeries.serviceInterface';
export * from './systemic-therapies.service';
import { SystemicTherapiesService } from './systemic-therapies.service';
export * from './systemic-therapies.serviceInterface';
export * from './terminology.service';
import { TerminologyService } from './terminology.service';
export * from './terminology.serviceInterface';
export * from './tumor-markers.service';
import { TumorMarkersService } from './tumor-markers.service';
export * from './tumor-markers.serviceInterface';
export const APIS = [AuthService, FamilyHistoriesService, GenomicSignaturesService, GenomicVariantsService, LifestylesService, MeasuresService, NeoplasticEntitiesService, PatientCasesService, PerformanceStatusService, RadiotherapiesService, RiskAssessmentsService, StagingsService, SurgeriesService, SystemicTherapiesService, TerminologyService, TumorMarkersService];
