export * from './adverse-events.service';
import { AdverseEventsService } from './adverse-events.service';
export * from './adverse-events.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './cohorts.service';
import { CohortsService } from './cohorts.service';
export * from './cohorts.serviceInterface';
export * from './comorbidities-assessments.service';
import { ComorbiditiesAssessmentsService } from './comorbidities-assessments.service';
export * from './comorbidities-assessments.serviceInterface';
export * from './family-histories.service';
import { FamilyHistoriesService } from './family-histories.service';
export * from './family-histories.serviceInterface';
export * from './genomic-signatures.service';
import { GenomicSignaturesService } from './genomic-signatures.service';
export * from './genomic-signatures.serviceInterface';
export * from './genomic-variants.service';
import { GenomicVariantsService } from './genomic-variants.service';
export * from './genomic-variants.serviceInterface';
export * from './lifestyles.service';
import { LifestylesService } from './lifestyles.service';
export * from './lifestyles.serviceInterface';
export * from './measures.service';
import { MeasuresService } from './measures.service';
export * from './measures.serviceInterface';
export * from './neoplastic-entities.service';
import { NeoplasticEntitiesService } from './neoplastic-entities.service';
export * from './neoplastic-entities.serviceInterface';
export * from './patient-cases.service';
import { PatientCasesService } from './patient-cases.service';
export * from './patient-cases.serviceInterface';
export * from './performance-status.service';
import { PerformanceStatusService } from './performance-status.service';
export * from './performance-status.serviceInterface';
export * from './radiotherapies.service';
import { RadiotherapiesService } from './radiotherapies.service';
export * from './radiotherapies.serviceInterface';
export * from './risk-assessments.service';
import { RiskAssessmentsService } from './risk-assessments.service';
export * from './risk-assessments.serviceInterface';
export * from './stagings.service';
import { StagingsService } from './stagings.service';
export * from './stagings.serviceInterface';
export * from './surgeries.service';
import { SurgeriesService } from './surgeries.service';
export * from './surgeries.serviceInterface';
export * from './systemic-therapies.service';
import { SystemicTherapiesService } from './systemic-therapies.service';
export * from './systemic-therapies.serviceInterface';
export * from './terminology.service';
import { TerminologyService } from './terminology.service';
export * from './terminology.serviceInterface';
export * from './therapy-lines.service';
import { TherapyLinesService } from './therapy-lines.service';
export * from './therapy-lines.serviceInterface';
export * from './treatment-responses.service';
import { TreatmentResponsesService } from './treatment-responses.service';
export * from './treatment-responses.serviceInterface';
export * from './tumor-boards.service';
import { TumorBoardsService } from './tumor-boards.service';
export * from './tumor-boards.serviceInterface';
export * from './tumor-markers.service';
import { TumorMarkersService } from './tumor-markers.service';
export * from './tumor-markers.serviceInterface';
export * from './vitals.service';
import { VitalsService } from './vitals.service';
export * from './vitals.serviceInterface';
export const APIS = [AdverseEventsService, AuthService, CohortsService, ComorbiditiesAssessmentsService, FamilyHistoriesService, GenomicSignaturesService, GenomicVariantsService, LifestylesService, MeasuresService, NeoplasticEntitiesService, PatientCasesService, PerformanceStatusService, RadiotherapiesService, RiskAssessmentsService, StagingsService, SurgeriesService, SystemicTherapiesService, TerminologyService, TherapyLinesService, TreatmentResponsesService, TumorBoardsService, TumorMarkersService, VitalsService];
