export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './cancer-patients.service';
import { PatientCasesService } from './cancer-patients.service';
export * from './cancer-patients.serviceInterface';
export * from './terminology.service';
import { TerminologyService } from './terminology.service';
export * from './terminology.serviceInterface';
export const APIS = [AuthService, PatientCasesService, TerminologyService];
