# Generated by Django 5.1 on 2025-04-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminology", "0008_cancertopographygroup_geneexon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneexon",
            name="gene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exons",
                to="terminology.gene",
            ),
        ),
    ]
