# Generated by Django 5.1 on 2025-01-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0008_tumorboardrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MolecularTumorBoardRecommendation',
        ),
        migrations.CreateModel(
            name='MolecularTumorBoardRecommendation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('terminology.tumorboardrecommendation',),
        ),
    ]
