/**
 * NinjaAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodedConcept } from './coded-concept';


export interface CancerPatientOut { 
    id: string;
    created_at: string;
    updated_at: string;
    /**
     * Pseudoidentifier of the patient
     */
    pseudoidentifier: string;
    race?: CodedConcept | null;
    birthsex?: CodedConcept | null;
    gender_identity?: CodedConcept | null;
    /**
     * Gender for administrative purposes
     */
    gender: CodedConcept;
    /**
     * Date of birth
     */
    birthdate: string;
    is_deceased?: boolean | null;
}

