/**
 * POP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSchema } from './user-schema';


export interface UserTokenSchema { 
    token: string;
    user: UserSchema;
    token_exp_date: string | null;
}

