# Generated by Django 5.1 on 2025-05-26 11:46

from django.db import migrations

import onconova.core.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_access_level"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", onconova.core.auth.models.QueryablePropertiesUserManager()),
            ],
        ),
    ]
    ]
