# Generated by Django 5.1 on 2025-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shareable',
            field=models.BooleanField(help_text='Whether user has consented to its data to be shared with other Onconova instances', null=True, verbose_name='Shareable'),
        ),
    ]
