# Generated by Django 5.1 on 2025-03-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0002_remove_systemictherapy_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comorbiditiesassessment',
            old_name='indexCondition',
            new_name='index_condition',
        ),
    ]
