# Generated by Django 5.1 on 2024-12-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0002_neoplasticentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neoplasticentity',
            name='related_primary',
            field=models.ForeignKey(blank=True, help_text='Reference to the primary neoplasm of which the neoplasm(s) originated from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='oncology.neoplasticentity', verbose_name='Related primary neoplasm'),
        ),
    ]
