# Generated by Django 5.1 on 2024-12-13 12:44

import pop.core.fields
import pop.core.measures
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0004_alter_lymphomastaging_modifiers_tumormarker'),
        ('terminology', '0003_tumormarkeranalyte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tumormarker',
            name='tumor marker must at least have one value',
        ),
        migrations.RemoveField(
            model_name='tumormarker',
            name='classification',
        ),
        migrations.AddField(
            model_name='tumormarker',
            name='combined_positive_score',
            field=pop.core.fields.MeasurementField(blank=True, help_text='The number of PD-L1 positive cells, including tumor cells, lymphocytes, and macrophages divided by the total number of viable tumor cells multiplied by 100', measurement=pop.core.measures.Fraction, null=True, verbose_name='Combined Positive Score (CPS)'),
        ),
        migrations.AddField(
            model_name='tumormarker',
            name='immune_cell_score',
            field=models.CharField(blank=True, choices=[('IC0', 'IC0'), ('IC1', 'IC1'), ('IC2', 'IC2'), ('IC3', 'IC3')], help_text='Categorization of the percentage of PD-L1 positive immune cells', max_length=50, null=True, verbose_name='Immune Cells Score (ICS)'),
        ),
        migrations.AddField(
            model_name='tumormarker',
            name='immunohistochemical_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('indeterminate', 'Indeterminate')], help_text='Categorization of the number of analyte-positive cells in a sample', max_length=50, null=True, verbose_name='Immunohistochemical Score'),
        ),
        migrations.AddField(
            model_name='tumormarker',
            name='nuclear_expression_status',
            field=models.CharField(blank=True, choices=[('intact', 'Intact'), ('loss', 'Loss'), ('indeterminate', 'Indeterminate')], help_text='Categorization of the status of expression of the analyte', max_length=50, null=True, verbose_name='Nuclear expression status'),
        ),
        migrations.AddField(
            model_name='tumormarker',
            name='presence',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('indeterminate', 'Indeterminate')], help_text='Whether an analyte has tested positive or negative.', max_length=50, null=True, verbose_name='Presence'),
        ),
        migrations.AddField(
            model_name='tumormarker',
            name='tumor_proportion_score',
            field=models.CharField(blank=True, choices=[('TC0', 'TC0'), ('TC1', 'TC1'), ('TC2', 'TC2'), ('TC3', 'TC3')], help_text='Categorization of the percentage of cells in a tumor that express PD-L1', max_length=50, null=True, verbose_name='Immune Cells Score (ICS)'),
        ),
        migrations.AddConstraint(
            model_name='tumormarker',
            constraint=models.CheckConstraint(condition=models.Q(('mass_concentration__isnull', False), ('arbitrary_concentration__isnull', False), ('substance_concentration__isnull', False), ('fraction__isnull', False), ('multiple_of_median__isnull', False), ('tumor_proportion_score__isnull', False), ('immune_cell_score__isnull', False), ('combined_positive_score__isnull', False), ('immunohistochemical_score__isnull', False), ('presence__isnull', False), ('nuclear_expression_status__isnull', False), _connector='OR'), name='tumor marker must at least have one value'),
        ),
    ]
