# Generated by Django 5.1 on 2025-01-07 12:22

import pop.core.measures.fields
import measurement.measures.mass
import pop.core.measures
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0010_alter_systemictherapymedication_systemic_therapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_mass',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage of the medication expressed in a fixed mass (if revelant/appliccable)', measurement=measurement.measures.mass.Mass, null=True, verbose_name='Dosage - Fixed Mass'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_mass_concentration',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage of the medication expressed in mass concentration (if revelant/appliccable)', measurement=pop.core.measures.MassConcentration, null=True, verbose_name='Dosage - Mass concentration'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_mass_surface',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage of the medication expressed in a mass per body surface area (if revelant/appliccable)', measurement=pop.core.measures.MassPerArea, null=True, verbose_name='Dosage - Mass per body surface'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_rate_mass',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage rate of the medication expressed in a fixed mass (if revelant/appliccable)', measurement=pop.core.measures.MassPerTime, null=True, verbose_name='Dosage rate - Fixed Mass'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_rate_mass_concentration',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage rate of the medication expressed in mass concentration (if revelant/appliccable)', measurement=pop.core.measures.MassConcentrationPerTime, null=True, verbose_name='Dosage rate - Mass concentration'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_rate_mass_surface',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage rate of the medication expressed in a mass per body surface area (if revelant/appliccable)', measurement=pop.core.measures.MassPerAreaPerTime, null=True, verbose_name='Dosage rate - Mass per body surface'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_rate_volume',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage rate of the medication expressed in a volume (if revelant/appliccable)', measurement=pop.core.measures.VolumePerTime, null=True, verbose_name='Dosage rate - Volume'),
        ),
        migrations.AddField(
            model_name='systemictherapymedication',
            name='dosage_volume',
            field=pop.core.measures.fields.MeasurementField(blank=True, help_text='Dosage of the medication expressed in a volume (if revelant/appliccable)', measurement=pop.core.measures.Volume, null=True, verbose_name='Dosage - Volume'),
        ),
    ]
