# Generated by Django 5.1 on 2025-01-15 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0018_alter_comorbiditiesassessment_date_vitals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genomicvariant',
            old_name='coding_hgsv',
            new_name='coding_hgvs',
        ),
        migrations.RenameField(
            model_name='genomicvariant',
            old_name='genomic_hgsv',
            new_name='genomic_hgvs',
        ),
        migrations.RenameField(
            model_name='genomicvariant',
            old_name='protein_hgsv',
            new_name='protein_hgvs',
        ),
        migrations.AlterField(
            model_name='genomicvariant',
            name='genomic_refseq',
            field=models.CharField(blank=True, help_text="\n            Identifier the transcript reference sequence, which includes transcribed and non transcribed stretches. \n            Can be an NCBI's RefSeq ('NC_...' or 'NG...'), and LRG ('LRG...')", max_length=200, null=True, validators=[django.core.validators.RegexValidator('^(?:NG|NC|LRG)(.*)$', 'The string should be a valid transcript RefSeq identifier.')], verbose_name='Genomic RefSeq'),
        ),
        migrations.AlterField(
            model_name='genomicvariant',
            name='transcript_refseq',
            field=models.CharField(blank=True, help_text="\n            Identifier the transcript reference sequence, which includes transcribed and non transcribed stretches. \n            Can be an NCBI's RefSeq ('NM_...' or 'NG...'), Ensembl ('ENST...'), and LRG ('LRG...' plus 't1' to indicate transcript)", max_length=200, null=True, validators=[django.core.validators.RegexValidator('^(?:NM|NG|ENST|LRG)(.*)$', 'The string should be a valid transcript RefSeq identifier.')], verbose_name='Transcript RefSeq'),
        ),
    ]
