# Generated by Django 5.1 on 2025-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0026_remove_moleculartherapeuticrecommendation_action_and_more'),
        ('terminology', '0009_delete_moleculartumorboardrecommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculartherapeuticrecommendation',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Drugs(s) being recommended', related_name='+', to='terminology.antineoplasticagent', verbose_name='Drug(s)'),
        ),
    ]
