# Generated by Django 5.1 on 2025-01-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0027_alter_moleculartherapeuticrecommendation_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverseevent',
            name='is_expected',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='is_serious',
        ),
    ]
