# Code autogenerated by Fhircraft 0.6.4 on 2026-02-20 14:15:12.065413.

from fhircraft.fhir.resources.datatypes.R4.core import Observation
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import (
    Annotation,
    BackboneElement,
    CodeableConcept,
    Coding,
    Extension,
    Meta,
    Quantity,
    Reference,
)
from fhircraft.fhir.resources.base import FHIRSliceModel, FhirBaseModelKind
from fhircraft.fhir.resources.datatypes.primitives import (
    Code,
    DateTime,
    Instant,
    String,
)
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import (
    get_type_choice_value_by_base,
    validate_FHIR_element_fixed_value,
    validate_FHIR_element_pattern,
    validate_model_constraint,
    validate_slicing_cardinalities,
    validate_type_choice_element,
)

NoneType = type(None)
from onconova.interoperability.fhir.models.GenomicsBase import (
    GenomicsBase,
)


class OnconovaHomologousRecombinationDeficiency(GenomicsBase):
    """
        A profile representing homologous recombination deficiency for a cancer patient.

    This profile extends the GenomicsReporting IG [GenomicsBase profile](http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomics-base) to include specific constraints and extensions relevant to Onconova.

    **Conformance:**

    Observation resources representing a homologous recombination deficiency obtained through genomic testing in the scope of Onconova SHALL conform to this profile. Any resource intended to conform to this profile SHOULD populate `meta.profile` accordingly.
    """

    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-homologous-recombination-deficiency"

    meta: Optional[Meta] = Field(
        title="Meta",
        description="Metadata about the resource.",
        default_factory=lambda: Meta(
            profile=[
                "http://onconova.github.io/fhir/StructureDefinition/onconova-homologous-recombination-deficiency"
            ]
        ),
    )
    status: Optional[Code] = Field(
        description="Not used in this profile",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Type of observation (code / type)",
        default_factory=lambda: CodeableConcept(
            coding=[
                Coding(
                    code="C120465",
                    display="Homologous Recombination Deficiency",
                    system="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl",
                )
            ]
        ),
    )
    subject: Optional[Reference] = Field(
        description="The cancer patient associated with this signature",
        default=None,
    )
    focus: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    issued: Optional[Instant] = Field(
        description="Not used in this profile",
        default=None,
    )
    performer: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    interpretation: Optional[List[CodeableConcept]] = Field(
        description="Not used in this profile",
        default=None,
    )
    bodySite: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    specimen: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    device: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    referenceRange: Optional[List[BackboneElement]] = Field(
        description="Not used in this profile",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    component: Optional[List[BackboneElement]] = Field(
        description="Not used in this profile",
        default=None,
    )

    @property
    def effective(self):
        return get_type_choice_value_by_base(
            self,
            base="effective",
        )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("code",), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):
        return validate_FHIR_element_pattern(
            cls,
            value,
            pattern=CodeableConcept(
                coding=[
                    Coding(
                        code="C120465",
                        display="Homologous Recombination Deficiency",
                        system="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl",
                    )
                ]
            ),
        )

    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["DateTime"],
            field_name_base="effective",
            required=True,
            non_allowed_types=["Period", "Timing", "Instant"],
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["Quantity"],
            field_name_base="value",
            required=True,
            non_allowed_types=[
                "CodeableConcept",
                "String",
                "Boolean",
                "Integer",
                "Range",
                "Ratio",
                "SampledData",
                "Time",
                "DateTime",
                "Period",
            ],
        )

    @model_validator(mode="after")
    def FHIR_o_sig_req_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="subject.exists()",
            human="The subject element is required and must be provided.",
            key="o-sig-req-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_sig_req_2_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="effectiveDateTime.exists() and effectiveDateTime.hasValue()",
            human="The effectiveDateTime element is required and must be provided.",
            key="o-sig-req-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_sig_req_3_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="valueQuantity.exists()",
            human="The valueQuantity element is required and must be provided.",
            key="o-sig-req-3",
            severity="error",
        )
