site_name: Onconova
site_description: Precision Oncology Platform
site_url: http://0.0.0.0/docs
site_author: Luis Fabregas
copyright: Copyright &copy; 2025 - Luis Fabregas
repo_url: https://github.com/onconova/onconova
docs_dir: src
theme:
  name: material
  logo: assets/img/logo.svg
  favicon: assets/favicon-dark-theme.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.expand
    - navigation.path    
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
plugins:
  - search
  - mike
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - document-dates:
      exclude:                
        - index.md
  - literate-nav:
      nav_file: SUMMARY.md
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/gen_db_schema_page.py
        - scripts/gen_repo_pages.py
        - scripts/gen_credits_table.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true   
            show_root_full_path: true     
            show_attribute_values: false
            parameter_headings: true
            show_if_no_docstring: true
            merge_init_into_class: true
            show_symbol_type_heading: true
            signature_crossrefs: true
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://docs.djangoproject.com/en/5.2/objects.inv
            - https://django-queryable-properties.readthedocs.io/en/stable/objects.inv

markdown_extensions:
  - neoteroi.cards
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
extra:
  version:
    provider: mike
extra_css:
  - assets/css/style.css
  - assets/css/home.css
  - assets/css/client-docs.css
  - assets/css/neoteroi-mkdocsoad.css
  - assets/css/neoteroi-mkdocs.min.css