# Generated by Django 5.1 on 2025-08-04 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_cohortevent_id_alter_cohortevent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cohortevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', null=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datasetevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', null=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectdatamanagergrant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectdatamanagergrant',
            name='project',
            field=models.ForeignKey(help_text='Project under which the permission is granted', on_delete=django.db.models.deletion.CASCADE, related_name='edit_permissions', to='research.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectdatamanagergrantevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', null=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectdatamanagergrantevent',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='Project under which the permission is granted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='research.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the resource (UUID v4).', null=True, serialize=False),
        ),
    ]
