#
name: Dev Documentation Deployment

on:
  push:
    branches:
      - main
    tags-ignore: ['**']
    
permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
  
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install --upgrade pip
          pip install .
          pip install ../server

      - name: Setup Git CLI
        run: |
          git config --global user.name 'onconova'
          git config --global user.email 'onconova@users.noreply.github.com'

      - name: Build and deploy documentation
        run: |
          cd docs
          npx @compodoc/compodoc@1.1.26 -p ../client/tsconfig.doc.json -d ./src/compodoc/ -y src/assets/css/compodoc/ --hideGenerator --theme material
          git fetch https://github.com/onconova/docs.git main --depth=1
          mike deploy --push -r https://onconova:${{ secrets.ONCONOVA_DOCS_ACCESS_TOKEN }}@github.com/onconova/docs.git -b main dev
          mike set-default latest
