name: API Breaking Changes

on:
  pull_request:


env:
  CURRENT_BRANCH: ${{ github.head_ref }}
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  build-oas-artefacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Install required tools
        run: |
          npm install speccy -g
          npm install -g @openapitools/openapi-generator-cli@1.0.10-4.2.3

      - name: Clone repository from ${{ env.TARGET_BRANCH }} branch 
        uses: actions/checkout@v2
        with:
          path: 'original'
          ref: ${{ github.base_ref }}

      - name: Clone repository from ${{ env.CURRENT_BRANCH }} branch
        uses: actions/checkout@v2
        with:
          path: 'modified'
          ref: ${{ github.head_ref }}

      - name: Check if OAS from ${{ env.CURRENT_BRANCH }} is valid
        run: |
          npx @openapitools/openapi-generator-cli validate -i modified/client/openapi.json

      - name: Check if OAS from ${{ env.TARGET_BRANCH }} is valid
        run: |
          npx @openapitools/openapi-generator-cli validate -i original/client/openapi.json

      - name: Upload single OAS file from ${{ env.TARGET_BRANCH }}
        uses: actions/upload-artifact@v4
        with:
          name: original-spec
          path: original/client/openapi.json
          
      - name: Upload single OAS file from ${{ env.CURRENT_BRANCH }}
        uses: actions/upload-artifact@v4
        with:
          name: modified-spec
          path: modified/client/openapi.json

  build-report:
    needs: build-oas-artefacts
    runs-on: ubuntu-latest
    env:
      ORIGIN_SPEC: "original-spec/openapi.json"
      MODIFIED_SPEC: "modified-spec/openapi.json"
      SPECS_LOG: "breaking-changes.log"
      JSON_DIFF_FILE: "breaking-changes.json"
      GH_COMMENT_FILE: "Github-comment.md"
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install required tools
        run: |
          npm install openapi-diff -g

      - name: Download OAS files from artifacts
        uses: actions/download-artifact@v4

      - name: Restore permissions
        run: |
          chmod -R 777 ${{ env.ORIGIN_SPEC }}
          chmod -R 777 ${{ env.MODIFIED_SPEC }}

      - name: Generate report
        run: |
          openapi-diff ${{ env.ORIGIN_SPEC }} ${{ env.MODIFIED_SPEC }} | tee ${{ env.SPECS_LOG }}
          sed -n '1!p' ${{ env.SPECS_LOG }} > ${{ env.JSON_DIFF_FILE }}

      - uses: actions/upload-artifact@v4
        with:
          name: openapi-diff
          path: breaking-changes.json

      - name: Prepare comment on Github PR
        run: |
          sed -n '1p' ${{ env.SPECS_LOG }} >> ${{ env.GH_COMMENT_FILE }}
          printf "\n\n\`\`\`json\n" >> ${{ env.GH_COMMENT_FILE }}
          sed -n '1!p' ${{ env.SPECS_LOG }} >> ${{ env.GH_COMMENT_FILE }}
          printf "\n\`\`\`\n" >> ${{ env.GH_COMMENT_FILE }}

      - name: PR Comment
        run:
          gh pr comment $PRNUM --body-file ${{ env.GH_COMMENT_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
