name: API Breaking Changes

on:
  pull_request:


env:
  CURRENT_BRANCH: ${{ github.head_ref }}
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  build-oas-artefacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Install required tools
        run: |
          npm install speccy -g
          npm install -g @openapitools/openapi-generator-cli@1.0.10-4.2.3

      - name: Clone repository from ${{ env.TARGET_BRANCH }} branch 
        uses: actions/checkout@v2
        with:
          path: 'original'
          ref: ${{ github.base_ref }}

      - name: Clone repository from ${{ env.CURRENT_BRANCH }} branch
        uses: actions/checkout@v2
        with:
          path: 'modified'
          ref: ${{ github.head_ref }}

      - name: Check if OAS from ${{ env.CURRENT_BRANCH }} is valid
        run: |
          npx @openapitools/openapi-generator-cli validate -i modified/client/openapi.json

      - name: Check if OAS from ${{ env.TARGET_BRANCH }} is valid
        run: |
          npx @openapitools/openapi-generator-cli validate -i original/client/openapi.json

      - name: Upload single OAS file from ${{ env.TARGET_BRANCH }}
        uses: actions/upload-artifact@v4
        with:
          name: original-spec
          path: original/client/openapi.json
          
      - name: Upload single OAS file from ${{ env.CURRENT_BRANCH }}
        uses: actions/upload-artifact@v4
        with:
          name: modified-spec
          path: modified/client/openapi.json

  build-report:
    permissions:
      contents: read
      pull-requests: write
    needs: build-oas-artefacts
    runs-on: ubuntu-latest
    env:
      GH_COMMENT_FILE: "Github-comment.md"
    steps:

      - name: Download OAS files from artifacts
        uses: actions/download-artifact@v4

      - name: Detect breaking changes
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: original-spec/openapi.json
          revision: modified-spec/openapi.json

      - name: Generate changelog 
        uses: oasdiff/oasdiff-action/changelog@main
        with:
          base: original-spec/openapi.json
          revision: modified-spec/openapi.json
          format: markdown
          output-to-file: ${{ env.GH_COMMENT_FILE }}

      - name: PR Comment
        run:
          gh pr comment $PRNUM --body-file ${{ env.GH_COMMENT_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
