#
name: Dev Documentation Deployment

on:
  push:
    branches:
      - main
    tags-ignore: ['**']
    
permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPLOY_BOT_APP_ID }}
          private-key: ${{ secrets.DEPLOY_BOT_APP_KEY }}
          owner: onconova
          repositories: docs

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
  
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install --upgrade pip
          pip install .
          pip install ../server

      - name: Setup Deploy Bot User
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cd docs
          npx @compodoc/compodoc@1.1.26 -p ../client/tsconfig.doc.json -d ./src/compodoc/ -y src/assets/css/compodoc/ --hideGenerator --theme material
          git fetch https://x-access-token:$GITHUB_TOKEN@github.com/onconova/docs.git main --depth=1
          mike deploy --push -r https://x-access-token:$GITHUB_TOKEN@github.com/onconova/docs.git -b main dev 
